"""
TruthLens Chat API v1

API endpoints for communicating with the TruthLens Support Chatbot.
"""

from typing import List
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from app.services.chatbot import generate_chat_response

router = APIRouter(prefix="/api/v1/chat", tags=["Chat"])

class ChatMessage(BaseModel):
    role: str
    content: str

class ChatRequest(BaseModel):
    messages: List[ChatMessage]

class ChatResponse(BaseModel):
    response: str

@router.post("/message", response_model=ChatResponse)
async def send_message(request: ChatRequest):
    """
    Send a conversation thread to the TruthLens Assistant and receive a response.
    
    Args:
        request: The ChatRequest containing a list of structured messages.
        
    Returns:
        The text response generated by the AI Assistant.
    """
    if not request.messages:
        raise HTTPException(status_code=400, detail="Messages list cannot be empty")
        
    # Convert Pydantic models to dicts to pass into the service
    messages_list = [{"role": msg.role, "content": msg.content} for msg in request.messages]
    
    # Generate the response
    bot_response = await generate_chat_response(messages_list)
    
    return ChatResponse(response=bot_response)
